apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: test-selfsigned
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amolsontakke96@gmail.com
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: new-selfsigned-cert
spec:
  dnsNames:
    - wisecow.amolsontakke-testing.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
  annotations:
    cert-manager.io/cluster-issuer: "test-selfsigned"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - wisecow.amolsontakke-testing.com
    secretName: selfsigned-cert-tls
  rules:
  - host: "wisecow.amolsontakke-testing.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wisecow-service
            port:
              number: 80
