name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        eval $(minikube -p minikube docker-env)
        minikube version
        
    - name: Deploy to Minikube
      run: |
        kubectl config use-context minikube
        kubectl apply -f wisecow.yaml
        sudo minikube kubectl -- get pods -A
        
    - name: Test service URLs
      run: |
        minikube service list
        echo "Service URL: http://$(minikube ip):$(kubectl get service wisecow-service -o=jsonpath='{.spec.ports[0].nodePort}')"
