name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4
        
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker image
      run: |
           sudo docker build -t wisecow:latest .
           sudo docker tag wisecow:latest amolsontakke96/accuknox-devops-trainee-practical-assessment:latest
           sudo docker push amolsontakke96/accuknox-devops-trainee-practical-assessment:latest

    - name: Deploy to Kubernetes
      run: |
          sudo microk8s.kubectl apply -f certi-issuer-ingress.yaml
          sudo microk8s.kubectl wait --for=condition=ready pod -l app=wisecow
          sudo microk8s.kubectl get service
          sudo microk8s.kubectl get service wisecow-service
          echo "------------------opening the service------------------"
