name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      run: |
        minikube version
    
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status
        eval $(minikube -p minikube docker-env)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t accuknox-devops-trainee-practical-assessment:latest .

    - name: Push Docker image to Minikube
      run: |
        docker tag accuknox-devops-trainee-practical-assessment:latest amolsontakke96/accuknox-devops-trainee-practical-assessment:latest
        docker push amolsontakke96/accuknox-devops-trainee-practical-assessment:latest
    
    - name: Configure kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl
        kubectl version --client
        minikube kubectl -- get pods
        kubectl config use-context minikube
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f wisecow.yaml
        kubectl wait --for=condition=ready pod -l app=wisecow
        kubectl get pods -A
        minikube status
        minikube ip
        kubectl cluster-info
        kubectl get nodes
        minikube kubectl -- get pods
        
    - name: Test service URLs
      run: |
        minikube service list
        echo "Service URL: http://$(minikube ip):$(kubectl get service wisecow-service -o=jsonpath='{.spec.ports[0].nodePort}')"

        
