name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: amolsontakke96/Accuknox-DevOps-Trainee-Practical-Assessment
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Build image
      run: |
        minikube image build -t accuknox-devops-trainee-practical-assessment:latest .        
    - name: Deploy to minikube
      run:
        kubectl apply -f wisecow.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service wisecow-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service wisecow-service --url) 
