name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
        
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t amolsontakke96/accuknox-devops-trainee-practical-assessment:latest .
      
    - name: Push Docker image
      run: docker push amolsontakke96/accuknox-devops-trainee-practical-assessment:latest
    
    - name: Deploy to Kubernetes
      run: kubectl get pods -A
    
    - name: Set up kubectl
      run: kubectl get pods -A
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
          
    - name: Deploy to Kubernetes
      run: kubectl get pods -A
