name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Minikube
      uses: opsgang/ga-setup-minikube@v0.1.1

    - name: Set up Minikube
      run: |
        curl -LO https://github.com/kubernetes/minikube/releases/download/v1.4.0/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        mv minikube-linux-amd64 $HOME/bin/minikube
      env:
       PATH: $HOME/bin:$PATH
      
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status
        minikube version
        eval $(minikube -p minikube docker-env)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
         minikube-version: 1.33.1
         k8s-verison: 1.28.4

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f wisecow.yaml
        kubectl wait --for=condition=ready pod -l app=wisecow
        kubectl get pods -A
        kubectl get nodes
        minikube kubectl -- get pods
        
    - name: Test service URLs
      run: |
        minikube service list
        echo "Service URL: http://$(minikube ip):$(kubectl get service wisecow-service -o=jsonpath='{.spec.ports[0].nodePort}')"

        
