name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: v1.33.1
        driver: docker
      
    - name: Start Minikube
      run: |
        eval $(minikube -p minikube docker-env)
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f wisecow.yaml
        kubectl wait --for=condition=ready pod -l app=wisecow
        minikube kubectl -- get pods
        
    - name: Test service URLs
      run: |
        minikube service list
        echo "Service URL: http://$(minikube ip):$(kubectl get service wisecow-service -o=jsonpath='{.spec.ports[0].nodePort}')"
