name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
          repository: amolsontakke96/Accuknox-DevOps-Trainee-Practical-Assessment
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
      
    - name: Start Minikube
      run: |
        minikube start --driver=docker
        eval $(minikube -p minikube docker-env)
        minikube status
        kubectl get nodes
        minikube kubectl -- get pods
        kubectl apply -f wisecow.yaml
        kubectl wait --for=condition=ready pod -l app=wisecow
        kubectl get pods -A
